# Generated by Django 4.1.7 on 2024-05-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artifactName', models.CharField(max_length=255)),
                ('artifactName_Chinese', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('relicTime', models.CharField(blank=True, max_length=255, null=True)),
                ('relicTime_Chinese', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('material_Chinese', models.CharField(blank=True, max_length=255, null=True)),
                ('library', models.CharField(blank=True, max_length=255, null=True)),
                ('library_Chinese', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('size_Chinese', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('description_Chinese', models.CharField(blank=True, max_length=255, null=True)),
                ('moreUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'artifact',
                'managed': False,
            },
        ),
    ]
