# Generated by Django 4.1.7 on 2024-05-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact1',
            options={'managed': False},
        ),
    ]
